workflows:
  expo-android-build:
    name: Expo Android AAB Build
    max_build_duration: 45
    instance_type: mac_mini_m2

    environment:
      node: 18
      java: 17

    scripts:
      - name: Clean install
        script: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Install Expo CLI
        script: |
          npm install -g expo@latest

      - name: Expo prebuild
        script: |
          npx expo prebuild --platform android --non-interactive --clean

      - name: Build Release AAB
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/bundle/release/app-release.aab
