workflows:
  expo-android-build:
    name: Expo Android APK Build
    max_build_duration: 45
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: com.currencyapp.expo  # از app.json بردار
      # اگر Expo token داری، اینجا اضافه کن (اختیاری فعلاً):
      # groups:
      #   - expo_credentials

    scripts:
      - name: Install Node dependencies
        script: |
          npm install

      - name: Install Expo CLI globally
        script: |
          npm install -g expo-cli

      - name: Prebuild Expo for Android
        script: |
          npx expo prebuild --platform android --non-interactive --clean

      - name: Build Release APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/apk/release/app-release.apk  # اگر فقط یکی بود

    publishing:
      email:
        recipients:
          - amir@example.com  # ایمیل خودت رو عوض کن (یا این بخش رو کامل پاک کن اگر نمی‌خوای ایمیل بیاد)
        notify:
          success: true
          failure: true
