workflows:
  expo-android-build:
    name: Expo Android APK Build
    max_build_duration: 45
    instance_type: mac_mini_m2
    environment:
      java: 17
      vars:
        PACKAGE_NAME: com.currencyapp.expo
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      - name: Install Expo CLI globally
        script: |
          npm install -g expo-cli
      - name: Prebuild Expo for Android
        script: |
          npx expo prebuild --platform android --non-interactive --clean
      - name: Fix Gradle version
        script: |
          cd android
          sed -i 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-8.3-all.zip|' gradle/wrapper/gradle-wrapper.properties
      - name: Build Release APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - amir@example.com
        notify:
          success: true
          failure: true
